== Endringslogg [[Endringslogg]]

I tillegg til redaksjonelle justeringer som ikke loggføres her, er følgende kravsmessige endringer foretatt siden utgivelsen av v.0.9:

* *v.0.903*: Redaksjonell endring av tabellmalen for klasser og egenskaper, der radnavnet "Beskrivelse" er endret til "Anvendelse" som gjenspeiler direkte hensikten med den aktuelle raden i tabellene.

* *v.0.902*:
** Multiplisitet til egenskapen <<Klassifikasjon-erstatter>> endret fra 0..1 til 0..n, for å dekke behov for tilfeller der en klassifikasjon/versjon erstatter to eller flere klassifikasjoner/versjoner.
** Nye valgfrie egenskaper føyet til i <<Kategori>>, for å dekke behov for beskrivelse av hierarkiske relasjoner mellom kategorier: <<Kategori-bestårAv>>, <<Kategori-erDelAv>>, <<Kategori-generaliserer>> og <<Kategori-spesialiserer>>.

* *v.0.901*: Etter at det felles kontrollerte vokabularet https://data.norge.no/vocabulary/classification-item-change-type[Kategoriendringstyper] er blitt publisert, er "Merknad 1" og "Eksempel i RDF Turtle" til egenskapen https://informasjonsforvaltning.github.io/xkos-ap-no/#Kategorisammenligning-typeEndring[Kategorisammenligning – type endring (dct:type)] oppdatert ved å referere til det publiserte vokabularet. Kapitlet med forslag til et kontrollert vokabular for endringstyper er også fjernet.
