== Oversikt over klasser i XKOS-AP-NO [[Klasseoversikt]]

Følgende klasser er obligatoriske:

* <<Klassifikasjon>>

* <<Kategori>>

Følgende klasser er anbefalte:

* <<Klassifikasjonsnivå>>

Følgende klasser er valgfrie:

* <<Klassifikasjonssammenligning>>
* <<Kategorisammenligning>>

Følgende klasser i den forenklede modellen er utenfor omfanget til dette dokumentet å spesifisere:

* Klassene Begrep (`skos:Concept`) og Klassifikasjonsfamilie (`skos:Concept`): Disse er klasser som representerer begreper som er utenfor selve klassifikasjonen. Se _https://data.norge.no/specification/forvaltningsstandard-begrepsbeskrivelser/[Forvaltningsstandard for begrepsbeskrivelser]_ for hvordan begreper (`skos:Concept`) og begrepssamlinger (`skos:Collection`) beskrives, og _https://data.norge.no/specification/skos-ap-no-begrep/[SKOS-AP-NO-Begrep]_ for hvordan SKOS brukes til å uttrykke begreps- og begrepssamlingsbeskrivelser som er utformet i henhold til Forvaltningsstandard for begrepsbeskrivelser.

*	Liste (`rdf:List`): Dette er en RDF-teknisk konstruksjon som er brukt til å ha en «sortert liste», og som den vanlige brukeren ikke trenger å forholde seg til.

I kapitelene som beskriver den enkelte klassen, er egenskapene gruppert inn i obligatoriske (skal), anbefalte (bør) og valgfrie (kan) egenskaper og deretter sortert alfabetisk etter norske navn.
