== Om denne versjonen [[OmDenneVersjonen]]


Denne versjonen (v.0.8) er til åpen og uformell kommentering, med *[yellow-background]#kommenteringsfrist 10. desember 2021#*. Hvem som helst kan kommentere, og du trenger ikke å få dine innspill formelt forankret i din organisasjon.

Etter denne kommenteringsrunden vil det bli ferdigstilt en versjon 0.9 (med status «til utprøving») av spesifikasjonen, tentativt før årsskiftet 2021/2022.

Kjernegruppen som har utarbeidet dette utkastet ønsker dine innspill på bl.a. følgende:

. Innledende kapitler <<OmSpesifikasjonen>> og <<Innledning>>:
.. Generelt, gi oss tilbakemelding på om vi treffer de aktuelle målgruppene med disse innledende kapitlene, med konkrete forbedringsforslag hvis ikke.
.. Spesielt om <<Målgrupper>>: Savner du flere/andre målgrupper som spesifikasjonen også kan være nyttig for, i så fall hvem, hvorfor og hvordan?
. Omfang:
.. Er det noen behov som ikke er dekket av spesifikasjonen?
... Generelt, gi oss tilbakemelding på hva du mener mangler, med konkrete eksempler på behov, samt forslag til kravsnivå (obligatorisk/anbefalt/valgfri) og norske navn og beskrivelser.
... Spesielt, vi har lagt inn spørsmål under noen av egenskapene, der vi eksplisitt spør om du ser behov for de aktuelle egenskapene.
... Spesielt, dekker de endringstypene som er foreslått under <<ForslagTilEndringstyper>> de endringstypene du ser behov for?
.. Er noen av kravene (obligatoriske/anbefalte/valgfrie) for strenge eller for svake?
... Generelt, gi oss tilbakemelding på hva du mener er for strengt eller for svakt og hvorfor, og forslag til det du mener er riktig kravsnivå.
. Forståelighet:
.. Norske klasse- og egenskapsnavn. Selv om i utvekslingen/tilgjengeliggjøringen er det URIene (f.eks. `skos:prefLabel`) som skal tas med og ikke de norske klasse- og egenskapsnavnene, er det viktig at norske navn (f.eks. «anbefalt kodetekst» for egenskapen `skos:prefLabel`) er forståelige og meningsfulle for målgruppene av spesifikasjonen.
... Generelt, gi oss tilbakemelding på hva du mener kan forbedres, med konkrete forbedringsforslag samt kort begrunnelse.
... Spesielt ber vi om innspill til norske navn for endringstypene i <<ForslagTilEndringstyper>>.
.. Struktur:
... Generelt: gi oss tilbakemelding på hva du konkret mener bør kunne forbedres strukturmessig, f.eks. rekkefølgen mellom (under)kapitlene, «mal» for tabellene som nå er brukt til å beskrive klasser og egenskaper, osv.
.. Beskrivelser av klasser og egenskaper:
... Generelt, gi oss tilbakemelding på hva (beskrivelsen av hvilken klasse eller egenskap) du konkret mener bør kunne forbedres, med forslag til alternativ formulering.
.. Eksempler:
... Generelt, gi oss tilbakemelding på hva (eksempler til hvilken klasse/egenskap) du mener er feil eller uklare, eller mangler etc., med konkrete forbedringsforslag, ev. forslag til (alternative) eksempler.
.... Når det gjelder eksempler har kjernegruppen brukt følgende prioriteringsrekkefølge: obligatoriske – anbefalte – valgfrie egenskaper, og prosatekst (i tabellene) – eksempel i RDF Turtle (etter tabellene), og derfor ikke alt er eller vil være eksemplifisert.

Hvordan gir du tilbakemeldinger?

* Vi ber deg fortrinnsvis legge dine tilbakemeldinger inn som https://github.com/Informasjonsforvaltning/xkos-ap-no/issues[Issues på Github]. Dersom du ikke allerede har bruker på Github kan du opprette en bruker gratis.
* Du kan også sende oss dine tilbakemeldinger på e-post, til adressen mailto:informasjonsforvaltning@digdir.no[informasjonsforvaltning(at)digdir.no, XKOS-AP-NOv08].

Kjernegruppen har vært ledet av Digdir, med representanter fra Statistisk sentralbyrå, Skattedirektoratet, Arbeids- og velferdsdirektoratet, Brønnøysundregistrene og Statens kartverk.
