name: build adocs and publish v1 to staging

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-staging:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/xkos-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://staging.fellesdatakatalog.digdir.no
      ontology: xkos-ap-no
      ontology-type: specification
      files: |
        docs/index.html text/html nb
        docs/files/xkos-ap-no.pdf application/pdf nb files/xkos-ap-no.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
        docs/images/Eksempel1Næringsgruppering.png image/png nb images/Eksempel1Næringsgruppering.png
        docs/images/Eksempel2NæringsgrupperingHovedversjoner.png image/png nb images/Eksempel2NæringsgrupperingHovedversjoner.png
        docs/images/ForenkletModell-XKOS-AP-NO-Obligatoriske.png image/png nb images/ForenkletModell-XKOS-AP-NO-Obligatoriske.png
        docs/images/ForenkletModell-XKOS-AP-NO-ObligatoriskeOgAnbefalte.png image/png nb images/ForenkletModell-XKOS-AP-NO-ObligatoriskeOgAnbefalte.png
        docs/images/ForenkletModell-XKOS-AP-NO.png image/png nb images/ForenkletModell-XKOS-AP-NO.png
        docs/images/KlassenKategori.png image/png nb images/KlassenKategori.png
        docs/images/KlassenKategorisammenligning.png image/png nb images/KlassenKategorisammenligning.png
        docs/images/KlassenKlassifikasjon.png image/png nb images/KlassenKlassifikasjon.png
        docs/images/KlassenKlassifikasjonsnivå.png image/png nb images/KlassenKlassifikasjonsnivå.png
        docs/images/KlassenKlassifikasjonssammenligning.png image/png nb images/KlassenKlassifikasjonssammenligning.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}