name: build adocs and publish to GitHub pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - develop
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Update submodules to latest main
        run: |
          git submodule foreach --recursive git fetch origin
          git submodule foreach --recursive git checkout origin/main

      - name: Build html
        id: adocbuild
        uses: docker://asciidoctor/docker-asciidoctor:1.106@sha256:6266e05784c2d8ece9d9fe5e593b12c3beebebbc467135fd6f4a56269c93cea3
        with:
          args: bash -c "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: docker://asciidoctor/docker-asciidoctor:1.106@sha256:6266e05784c2d8ece9d9fe5e593b12c3beebebbc467135fd6f4a56269c93cea3
        with:
          args: bash -c "asciidoctor-pdf -D docs -o files/xkos-ap-no.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Deploy
        if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
